os: linux
dist: focal
language: cpp

install:
 - sudo apt-get update
 - sudo apt-get install --yes libgtest-dev
 - sudo apt-get install --yes gcovr
 - sudo apt install valgrind -y
 - sudo apt install cppcheck -y

jobs:
  - stage: Build
    script:
      - cmake -B build
      - make -C build
  - stage: Test
    script:
      - cd build
      - ctest --output-on-failure
      - cd ..
  - stage: Sanitaize
    script:
      - cmake -B build_s -DSANITAIZE=1
      - cmake -B build_p -DSANITAIZE=1 -DBUILD_PARAL=1
      - make -C build_s
      - make -C build_p
      - cppcheck project/src/* project/lib/parallel_sum/* project/lib/sequential_sum/* --error-exitcode=1
      - echo -e "1 2 3\n4 5 6\n7 8 9\n\n" > tmp.txt
      - valgrind ./build_s/yoyo tmp.txt --leak-check=full --tool=memcheck
      - valgrind ./build_p/yoyo tmp.txt --leak-check=full --tool=memcheck
