dist:     trusty
sudo:     required

language: c      

os:
  - linux

compiler:
  - gcc

env:
  global:
    - CODECOV_TOKEN='4a026a83-7947-490c-ae79-5046e4773a2d'

addons:
  apt:
    packages:
      - lcov
      - valgrind
      - cppcheck
      - make
      - cmake

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake .
  - make
  - ctest --output-on-failure

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ctest; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ./task1.out grass 1; fi
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --error-exitcode=1 -I project/include ./project/tst ./project/src ./project/include/*.h; fi
  
after_success:
  - bash <(curl -s https://codecov.io/bash)