version: 2
name: CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          sudo apt install -y libgtest-dev
          cmake -B build/
          make -C build/
