name: CI

on:
  push:
    branches: [ task2-solution ]
  pull_request:
    branches:
     - task2-solution
     - task2
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: echo lmao
